create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text,
  email text,
  score bigint
);


alter table public.leaderboard enable row level security;

-- READ policy

create policy "Allow public read access"
on public.leaderboard
for select
using (true);

-- WRITE policy

create policy "Allow public insert"
on public.leaderboard
for insert
with check (true);