-- ===============================================================
-- ELECTRON GAME - SUPABASE MIGRATION
-- ===============================================================

-- ---------------------------------------------------------------
-- LEADERBOARD TABLE
-- ---------------------------------------------------------------

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text,
  email text,
  score bigint
);

-- Enable RLS
alter table public.leaderboard enable row level security;

-- Allow anyone to read leaderboard
create policy "Allow public read access"
on public.leaderboard
for select
using (true);

-- Allow anyone to insert scores
create policy "Allow public insert"
on public.leaderboard
for insert
with check (true);

-- ---------------------------------------------------------------
-- ADMINS TABLE (whitelist for admin panel access)
-- ---------------------------------------------------------------

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  email text unique not null
);

-- Enable RLS
alter table public.admins enable row level security;

-- Allow authenticated users to read (to check if they're admin)
create policy "Authenticated users can read admins"
on public.admins
for select
to authenticated
using (true);

-- ---------------------------------------------------------------
-- INSERT YOUR ADMIN(S) HERE
-- ---------------------------------------------------------------

-- Replace with your admin email(s)
-- insert into public.admins (email) values ('admin@example.com');

-- ---------------------------------------------------------------
-- NOTES
-- ---------------------------------------------------------------
-- 
-- Admin users must also exist in Supabase Auth:
-- 1. Go to Supabase Dashboard → Authentication → Users
-- 2. Click "Add user" → "Create new user"
-- 3. Enter email + password
-- 4. Add the same email to the admins table above
--create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  email text unique not null
);